Challenge Solved
PlatziMaster/challenge-javascript-10 pull request #6
Opened 2020-03-31 20:40 UTC by ealexisaraujo

> * [x]  Usando reduce encontrar el numero más pequeño.
> * [x]  Usando reduce encontrar el numero más grande.
> * [x]  Obtener el promedio de un array.
> * [x]  Plus: Crear un array de 1000 números fake generados por la librería faker y probar las funciones.

2020-04-04 03:36 UTC, hyfi06 requested changes
Some comments

2020-04-04 03:36 UTC, hyfi06 commented on src/demo6.js
> +    0,
No es necesario iniciar en 0

2020-04-04 03:36 UTC, hyfi06 commented on src/demo6.js
> +  });
Pero esto crea un array de objetos, no de números

2020-04-11 18:48 UTC, ealexisaraujo commented
Gracias @hyfi06 resuelto

2022-03-04 01:39 UTC, ealexisaraujo reviewed
test

2022-08-29 22:49 UTC, closed without merging